# Generated by Django 6.1.1 on 2026-09-22 07:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('location_description', models.CharField(blank=True, help_text='Optional landmark or additional location information.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=30)),
                ('name', models.CharField(help_text='Example: Lagankhel - Gongabu', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_fare', models.DecimalField(blank=True, decimal_places=2, help_text='Optional base/estimated fare in NPR.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_bidirectional', models.BooleanField(default=True, help_text='Whether the route can be travelled in both directions.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='routes.operator')),
            ],
            options={
                'ordering': ['route_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order of this stop within the route.')),
                ('distance_from_previous', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from the previous stop in kilometres.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='routes.busroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='routes.busstop')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='busroute',
            constraint=models.UniqueConstraint(fields=('operator', 'route_number', 'name'), name='unique_operator_route'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='unique_route_sequence'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'stop'), name='unique_route_stop'),
        ),
    ]
